#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
client:
 peers:
  # peer0
  - host: "localhost"
    port: 7051
    eventHost: "localhost"
    eventPort: 7053
    primary: true
    tls:
      # Certificate location absolute path
      certificate: "$GOPATH/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      serverHostOverride: "peer0.org1.example.com"

 # Note, despite not using fabric-ca, this ID is what gets used as the MSP ID in the transactions
 # So we must set it here
 fabricCA:
  id: Org1MSP

 tls:
  enabled: true

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 orderer:
  host: "localhost"
  port: 7050
  tls:
    # Certificate location absolute path
    certificate: "$GOPATH/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
    serverHostOverride: "orderer.example.com"

 logging:
  level: info

 cryptoconfig:
  path: "$GOPATH/src/github.com/hyperledger/fabric-samples/first-network/crypto-config"
